apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::824403382669:user/cl-portfolio
      username: cl-portfolio
      groups:
        - system:masters
